version: '3.8'

services: 
  app:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    image: vega-backend
    volumes:
      - .:/var/www/html

    ports:
      - "8080:8080"

    # Overrides default command so things don't shut down after the process ends.
    command: /postCreateCommand.sh

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks:
      - sail

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    networks:
      - sail

  # Add phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: mariadb
      PMA_PASSWORD: mariadb
    networks:
      - sail
    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  
volumes:
  mariadb-data:

networks:
    sail:
        driver: bridge