version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    image: vega-backend-2
    volumes:
      - .:/app
    ports:
      - "8080:80"
    user: "${UID}:${GID}"

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks:
      - sail

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    networks:
      - sail

  # Add phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: mariadb
      PMA_PASSWORD: mariadb
    networks:
      - sail

volumes:
  mariadb-data:

networks:
    sail:
        driver: bridge
